### PR TITLE
Look for Python syntax errors or undefined names

### PR DESCRIPTION
**Pull request by cclauss**
* http://flake8.pycqa.org with find syntax errors and undefined names that can halt your program.
    * `--select=E901,E999,F821,F822,F823` focuses the tool on the most critical issues
* Fxxx codes are here: http://flake8.pycqa.org/en/latest/user/error-codes.html
* Other codes are here: https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes
* The output is here: https://travis-ci.org/astorfi/TensorFlow-World/builds/272817787

F821 is really helpful for finding Python 2 / 3 differences but also for typos, copy/paste errors, etc.

### CODE REVIEW

**Comment by astorfi** [comment]
@cclauss Thank you so much for your pull request ... Would you please explain more with some related links?

**Comment by cclauss** [comment]
Yes, sorry.  Done above.

**Comment by astorfi** [comment]
@cclauss Oh ... Thanks ... I have been working with that lately. Thank you so much for your suggestion and I would be happy to merge it.

**Comment by Ikavunik** [comment]
69el emes olol yrax

**Pull request merged**
